preset: laravel

enabled:
    - length_ordered_imports
    - concat_with_spaces
    - blank_line_before_return

disabled:
    - alpha_ordered_imports
    - concat_without_spaces
    - laravel_phpdoc_alignment
    - laravel_phpdoc_order
